# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mchua <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/05 20:46:50 by mchua             #+#    #+#              #
#    Updated: 2023/09/27 19:47:51 by mchua            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
SRCS = srcs/ft_atoi.c \
	srcs/ft_bzero.c \
	srcs/ft_isalnum.c \
	srcs/ft_isalpha.c \
	srcs/ft_isascii.c \
	srcs/ft_isdigit.c \
	srcs/ft_isprint.c \
	srcs/ft_itoa.c \
	srcs/ft_memchr.c \
	srcs/ft_memcmp.c \
	srcs/ft_memcpy.c \
	srcs/ft_memset.c \
	srcs/ft_putchar_fd.c \
	srcs/ft_putendl_fd.c \
	srcs/ft_putnbr_fd.c \
	srcs/ft_putstr_fd.c \
	srcs/ft_split.c \
	srcs/ft_strchr.c \
	srcs/ft_strdup.c \
	srcs/ft_strjoin.c \
	srcs/ft_strlcpy.c \
	srcs/ft_strlen.c \
	srcs/ft_strncmp.c \
	srcs/ft_strrchr.c \
	srcs/ft_strtrim.c \
	srcs/ft_substr.c \
	srcs/ft_tolower.c \
	srcs/ft_toupper.c \
	srcs/ft_strmapi.c \
	srcs/ft_striteri.c \
	srcs/ft_calloc.c \
	srcs/ft_strlcat.c \
	srcs/ft_memmove.c \
	srcs/ft_strnstr.c \
	srcs/ft_printf.c \
	srcs/ft_putchar.c \
	srcs/ft_puthex.c \
	srcs/ft_putnbr.c \
	srcs/ft_putstr.c \
	srcs/ft_putunsigned.c \
	srcs/ft_putvoid.c

BONUS_SRCS = srcs/ft_lstnew.c \
			srcs/ft_lstadd_front.c \
			srcs/ft_lstsize.c \
			srcs/ft_lstlast.c \
			srcs/ft_lstadd_back.c \
			srcs/ft_lstdelone.c \
			srcs/ft_lstclear.c \
			srcs/ft_lstiter.c \
			srcs/ft_lstmap.c
			

NAME = libft.a

CC = cc

CC_FLAGS = -Wall -Wextra -Werror -I.

OBJS = $(SRCS:.c=.o)

BONUS_OBJS = $(BONUS_SRCS:.c=.o)

$(NAME): $(OBJS)
	ar rc -o $(NAME) $(OBJS)
	
bonus: $(NAME) $(BONUS_OBJS)
	ar rc -o $(NAME) $(BONUS_OBJS)

%.o: %.c
	$(CC) $(CC_FLAGS) -c $< -o $@
	
all: $(NAME) bonus

clean:
	rm -rf $(OBJS)
	rm -rf $(BONUS_OBJS)
	
fclean:
	rm -rf $(OBJS)
	rm -rf $(BONUS_OBJS)
	rm -f $(NAME)

re: fclean all

.PHONY: clean fclean re all
